package com.example.vinaigrette;

public class Api {
    public static final String LOGIN = "depro/auth/login",
            REGISTER = "depro/auth/register",
            CATALOG = "depro/cron/catalog",
            NEWS_PROD = "depro/cron/news_prod",
            CATALOG_EX = "depro/cron/catalog_ex",
            PRODUCT_BARCODE = "depro/cron/product_barcode",
            PRODUCT_LIST = "depro/cron/product_list",
            PRODUCT_SEARCH = "depro/cron/product_search",
            PRODUCT_ID = "depro/cron/product_id",
            ANALOG_ID_PRODUCT = "depro/cron/product_analog",
            CHARACT_ID_PRODUCT = "depro/cron/product_charact",
            PROFILE = "depro/crontoken/profile",
            EDIT_PROF = "depro/auth/profile_edit",
            FITNESS = "depro/cron/fitness",
            SEND_ORDER = "depro/crontoken/send_order",
            FREEE_TIME = "depro/cron/freetime",
            NEWS = "depro/cron/news",
            NEWS_DETAIL = "depro/cron/news_detail",
            NEWS_SUBSCRIBE = "api/push/subscribe_news",
            NEWS_UNSUBSCRIBE = "api/push/unsubscribe_news",
            TOPIC_SUBSCRIBE = "api/push/subscribe_events",
            TOPIC_UNSUBSCRIBE = "api/push/unsubscribe_events",
            SEND_EVENTS_PUSH = "api/push/send_events",
            SEND_NEWS_PUSH = "api/push/send_news",
            EVENT = "depro/cron/events",
            SEND_FIT_TIME  = "depro/cron/fit_time";
}
